name: CI

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get changed files
        id: file_changes
        env:
          BASE_REF: ${{ github.base_ref }}
        run: |
          DIFF=$(git diff --name-only "origin/$BASE_REF" HEAD)
          echo "Diff between $BASE_REF and HEAD"
          echo "files=$(echo "$DIFF" | xargs echo)" >> "$GITHUB_OUTPUT"

      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0

      - uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install terraform-docs
        run: |
          curl -sSLo /tmp/terraform-docs.tar.gz \
            "https://github.com/terraform-docs/terraform-docs/releases/download/v0.22.0/terraform-docs-v0.22.0-linux-amd64.tar.gz"
          tar -xzf /tmp/terraform-docs.tar.gz -C /tmp terraform-docs
          sudo mv /tmp/terraform-docs /usr/local/bin/

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Execute pre-commit
        env:
          FILES: ${{ steps.file_changes.outputs.files }}
        run: |
          read -ra files <<< "$FILES"
          pre-commit run --color=always --show-diff-on-failure --files "${files[@]}"
